export const READER_DEFAULT_MAX_TURNS = 4;
export const READER_DEFAULT_MAX_TOOL_RESULT_CHARS = 8_000;
export const READER_DEFAULT_MAX_FINAL_CHARS = 10_000;

export const WRITER_DEFAULT_MAX_TURNS = 4;
export const WRITER_DEFAULT_MAX_TOOL_RESULT_CHARS = 8_000;
export const WRITER_DEFAULT_MAX_FINAL_CHARS = 10_000;

export const GIT_DEFAULT_MAX_TURNS = 4;
export const GIT_DEFAULT_MAX_TOOL_RESULT_CHARS = 8_000;
export const GIT_DEFAULT_MAX_FINAL_CHARS = 10_000;
